# Generated by Django 5.1 on 2024-08-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationid', models.TextField()),
                ('applicant', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=50)),
                ('cnn', models.CharField(max_length=50)),
                ('location_description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('blocklot', models.CharField(blank=True, max_length=20)),
                ('block', models.CharField(blank=True, max_length=10)),
                ('lot', models.CharField(blank=True, max_length=100)),
                ('permit', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=1000)),
                ('food_items', models.TextField(blank=True)),
                ('x_coordinate', models.TextField()),
                ('y_coordinate', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('schedule', models.URLField(blank=True)),
                ('dayshours', models.CharField(blank=True, max_length=255)),
                ('noi_sent', models.CharField(blank=True, max_length=50)),
                ('approved', models.CharField(blank=True, max_length=50)),
                ('received', models.CharField(blank=True, max_length=50)),
                ('prior_permit', models.IntegerField(blank=True, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('fire_prevention_districts', models.CharField(blank=True, max_length=50)),
                ('police_districts', models.CharField(blank=True, max_length=50)),
                ('supervisor_districts', models.CharField(blank=True, max_length=50)),
                ('zip_codes', models.CharField(blank=True, max_length=50)),
                ('neighborhoods', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
