# Generated by Django 5.1 on 2024-08-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='prior_permit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
